import { ApolloProvider } from "@apollo/client";
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import "swiper/css";
import client from "../core/config/apollo-client";
import ErrorBoundary from "../core/shared/ErrorBoundary";
import Layout from "../core/shared/layout/Layout";
import "../styles/globals.scss";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Hollofabrika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client}>
        <ChakraProvider>
          <ErrorBoundary>
            <Layout>
              <NestedLayout Component={Component} pageProps={pageProps} />
            </Layout>
          </ErrorBoundary>
        </ChakraProvider>
      </ApolloProvider>
    </>
  );
}

const NestedLayout = ({ Component, pageProps }: any) => {
  if (!Component) return;

  return Component.getLayout ? (
    Component.getLayout(<Component {...pageProps} />)
  ) : (
    <Component {...pageProps} />
  );
};

export default MyApp;
